apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-to2s
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-to2s@sha256:436943f40ed153f8b9699eab444de29d0e6f00b7c575e2bea2219f4bd1e7e3f3
        name: my-nodejs
        resources: {}
status: {}
